#配置服务的端口号
server:
  port: 8881

#jdbc 驱动和连接信息,url拼凑方式及选择需要充电
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: demodemo
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 0  # 连接池中的最小空闲连接
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000 # 连接超时时间（毫秒）


#mybatis映射信息，权威网站：http://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
#  type-aliases-package: com.example.bootdemo.mybatisdemo.entity

#日志打印级别
logging:
  level:
    com:
      example:
        bootdemo:
          mybatisdemo:
            mapper: debug
